---
- name: ubuntu
  ansible.builtin.include_tasks:
    file: ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu'
- name: debian
  ansible.builtin.include_tasks:
    file: debian.yml
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Debian'
- name: Install Fluent Bit
  ansible.builtin.package:
    name: fluent-bit
    state: present
- name: Render Fluent Bit Configuration
  ansible.builtin.template:
    src: fluent-bit.config.j2
    dest: /etc/fluent-bit/fluent-bit.conf
    owner: root
    group: root
    mode: '0640'
  notify: Reload Fluent Bit