---
- name: ubuntu
  ansible.builtin.include_tasks:
    file: ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu'
- name: Install CouchDB
  ansible.builtin.package:
    name: couchdb
    state: present
  notify: Reload couchdb
- name: Render Configuration
  ansible.builtin.template:
    src: pi-monger.ini.j2
    dest: /opt/couchdb/etc/local.d/10-pi-monger.ini
  notify: Reload couchdb
- name: Render VM configuration
  ansible.builtin.template:
    src: vm.args.j2
    dest: /opt/couchdb/etc/vm.args
  notify: Reload couchdb
