---
- name: Reload service
  ansible.builtin.systemd:
    daemon_reload: yes
    state: restarted
    name: node-red
    enabled: yes
    masked: no
    scope: system
- name: Install node modules
  become: true
  become_user: "node-red"
  ansible.builtin.command:
    cmd: npm ci --prefer-offline --no-audit
    chdir: /opt/{{ node_red_org }}/node-red
