---
- name: Reload service
  ansible.builtin.systemd:
    daemon_reload: yes
    state: restarted
    name: node-red
    enabled: yes
    masked: no
    scope: system
- name: Install node modules
  become: true
  become_user: "node-red"
  ansible.builtin.command:
    cmd: npm ci --prefer-offline --no-audit --omit=dev
    chdir: /opt/{{ node_red_org }}/node-red

- name: Reload apparmor
  ansible.builtin.command:
    cmd: apparmor_parser -r -T -W /etc/apparmor.d/opt.{{ node_red_org }}.node-red.service
  notify:
    - Enable apparmor profile

- name: Enable apparmor profile
  ansible.builtin.command:
    cmd: apparmor_parser -a /etc/apparmor.d/opt.{{ node_red_org }}.node-red.service
