---
- name: Ensure dependencies are present.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Download NodeSource's signing key.
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/signing-key-nodesource-repo.asc
    owner: root
    group: root
    mode: '0444'
  register: node_signing_key
- name: Add NodeSource repository.
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{node_signing_key.dest }}] https://deb.nodesource.com/node_{{ nodejs_version }} nodistro main"
    state: present
    filename: 'nodesource_{{ nodejs_version }}'
- name: Install Node.js
  ansible.builtin.package:
    name: "nodejs"
    state: "{{ nodejs_packages_state }}"
