---
- name: Add Envoy repository.
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/envoy-keyring.asc] https://apt.envoyproxy.io jammy main"
    state: present
    filename: 'envoy'
