---
- name: Install Oscap
  ansible.builtin.package:
    name: "{{ item}}"
    state: latest
  loop:
    - libopenscap8
    - unzip
    - bzip2
- name: Download SCAP Content
  ansible.builtin.get_url:
    url: https://github.com/ComplianceAsCode/content/releases/download/v{{ hardened_system_scap_content_version }}/scap-security-guide-{{ hardened_system_scap_content_version }}.zip
    dest: /dev/shm/ssg-debderived-{{ ansible_facts['distribution_version'] }}.zip
    owner: root
    group: root
    mode: '0644'
    checksum: "sha256:{{ hardened_system_scap_content_checksum }}"
    
- name: Create SCAP Content Directory
  ansible.builtin.file:
    state: directory
    recurse: true
    path: /usr/share/xml/scap/ssg/content
- name: Extract SCAP Content
  ansible.builtin.unarchive:
    src: /dev/shm/ssg-debderived-{{ ansible_facts['distribution_version'] }}.zip
    dest: /usr/share/xml/scap/ssg/content
    remote_src: yes
- name: Create OSCAP tmp Dir
  ansible.builtin.file:
    state: directory
    path: /dev/shm/oscap_tmp
- name: Scan System
  changed_when: false
  register: scan_results
  failed_when: scan_results.rc != 0 and scan_results.rc != 2
  ansible.builtin.command:
    cmd: oscap xccdf eval --profile {{ hardened_system_profile }} --results-arf /dev/shm/oscap_tmp/scan_results.xml /usr/share/xml/scap/ssg/content/scap-security-guide-{{ hardened_system_scap_content_version }}/ssg-ubuntu2204-ds.xml

- name: Generate Remediations
  changed_when: /dev/shm/oscap_tmp/remediation.xml is changed
  register: remediation_results
  ansible.builtin.command:
    cmd: oscap xccdf generate fix --profile {{ hardened_system_profile }} --template urn:xccdf:fix:script:ansible --output /dev/shm/oscap_tmp/remediation.xml  /usr/share/xml/scap/ssg/content/scap-security-guide-{{ hardened_system_scap_content_version }}/ssg-ubuntu2204-ds.xml

