---
- name: Install Oscap
  ansible.builtin.package:
    name: libopenscap8
    state: latest
- name: Download SCAP Content
  ansible.builtin.get_url:
    url: https://github.com/ComplianceAsCode/content/releases/download/v{{ hardened_system_scap_content_version }}/scap-security-guide-{{ hardened_system_scap_content_version }}.tar.bz2
    dest: /tmp/ssg-debderived-{{ ansible_facts['distribution_version'] }}.tar.bz2
    owner: root
    group: root
    mode: '0644'
- name: Create SCAP Content Directory
  ansible.builtin.file:
    state: directory
    recurse: true
    path: /usr/share/xml/scap/ssg/content
- name: Extract SCAP Content
  ansible.builtin.unarchive:
    src: /tmp/ssg-debderived-{{ ansible_facts['distribution_version'] }}.tar.bz2
    dest: /usr/share/xml/scap/ssg/content
    remote_src: yes
