---
- name: Render configuration
  ansible.builtin.template:
    src: "resolved.conf.j2"
    dest: "/etc/systemd/resolved.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd-resolved
