---
# once you are confident of stability, you may disable remote access to the system
# and manage soley through ansible_pull
hardened_system_disable_sshd: false
hardened_system_scap_content_version: "0.1.75"