---
# once you are confident of stability, you may disable remote access to the system
# and manage soley through ansible_pull
hardened_system_disable_sshd: false
hardened_system_scap_content_version: "0.1.75"
# the profile in the scap data source the system will adhere to
# you can inspect the profiles available with the following command:
# oscap info /usr/share/xml/scap/ssg/content/scap-security-guide-{{ version }}/ssg-ubuntu2204-ds.xml
hardened_system_profile: xccdf_org.ssgproject.content_profile_cis_level1_server
