---
- name: Ensure dest directory exists
  ansible.builtin.file:
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0700"
- name: Copy file
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
