---
- name: Render script
  ansible.builtin.template:
    src: pull.sh.j2
    dest: "{{ auto_pull_script_path }}"
    mode: '0540'
- name: Create cron job to re-run ansible-pull on configured interval
  ansible.builtin.cron:
    name: "{{ auto_pull_cron_job_name }}"
    minute: "{{ auto_pull_cron_job_minute }}"
    hour: "{{ auto_pull_cron_job_hour }}"
    day: "{{ auto_pull_cron_job_day }}"
    month: "{{ auto_pull_cron_job_month }}"
    weekday: "{{ auto_pull_cron_job_weekday }}"
    job: "{{ auto_pull_script_path }}"
- name: Disable cloud init
  ansible.builtin.include_tasks: disable-cloudinit.yaml
- name: Shred userdata
  ansible.builtin.include_tasks: shred-userdata.yaml
  when: ansible_facts['system'] | search('Raspberry Pi')
