---
- name: Create cron job to re-run ansible-pull every 10 minutes
  ansible.builtin.cron:
    name: "{{ auto_pull_cron_job_name }}"
    minute: "{{ auto_pull_cron_job_minute }}"
    hour: "{{ auto_pull_cron_job_hour }}"
    day: "{{ auto_pull_cron_job_day }}"
    month: "{{ auto_pull_cron_job_month }}"
    weekday: "{{ auto_pull_cron_job_weekday }}"
    job: "{{ auto_pull_cron_job_job }}"
