- name: Download Falco's signing key.
  ansible.builtin.get_url:
    url: https://falco.org/repo/falcosecurity-packages.asc
    dest: /etc/apt/signing-key-falco-repo.asc
    owner: root
    group: root
    mode: '0444'
  register: falco_signing_key
- name: Add Falco APT Repo
  ansible.builtin.apt_repository:
    repo: deb [signed-by={{falco_signing_key.dest }}] https://download.falco.org/packages/deb stable main
    state: present
    filename: 'falco'
