---
- name: Debian
  ansible.builtin.include_tasks:
    file: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
- name: Install Falco
  ansible.builtin.package:
    name: falco
    state: present
