---
- name: Ensure UFW installed
  ansible.builtin.package:
    name: ufw
    state: present
- name: Manage UFW State
  community.general.ufw:
    state: "enabled"
    policy: "{{ ufw_default_policy }}"
- name: Add Ingress Rules
  ansible.builtin.include_tasks: ingress-rule.yml
  with_items: "{{ ufw_ingress_rules }}"
- name: Add Egress Rules
  ansible.builtin.include_tasks: egress-rule.yml
  with_items: "{{ ufw_egress_rules }}"
