---
- name: Check if the system needs to be rebooted
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Schedule a reboot for midnight if needed
  become: true
  ansible.builtin.command:
    cmd: "shutdown -r {{ schedule_reboot_time}}"
  when: reboot_required.stat.exists
