---
- name: Render configuration file
  ansible.builtin.template:
    src: config.yml.j2
    dest: /etc/newrelic-infra.yml
    owner: root
    group: root
    mode: 0600
  notify: Reload newrelic-infra service

- name: Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu'
