---
- name: Render configuration file
  ansible.builtin.template:
    src: config.yml.j2
    dest: /etc/newrelic-infra.yml
    owner: root
    group: root
    mode: 0600
  notify: Reload newrelic-infra service
- name: Create logging settings directory
  ansible.builtin.file:
    state: directory
    recurse: yes
    path: /etc/newrelic-infra/logging.d
    owner: root
    group: root
    mode: 0700
- name: Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu'
- name: Debian
  ansible.builtin.include_tasks:
    file: debian.yml
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Debian'
- name: Install newrelic-infra agent
  ansible.builtin.package:
    name: newrelic-infra
    state: present
  notify: Reload newrelic-infra service