---
- ansible.builtin.include_role:
    name: newrelic.newrelic_install
    apply:
      environment:
        NEW_RELIC_API_KEY: "{{ newrelic_api_key }}"
        NEW_RELIC_ACCOUNT_ID: "{{ newrelic_account_id }}"
        NEW_RELIC_REGION: "{{ newrelic_region }}"
  vars:
    targets: "{{ newrelic_targets }}"
