- name: Download NewRelic's signing key.
  ansible.builtin.get_url:
    url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg 
    dest: /etc/apt/keyrings/newrelic-infra.gpg
    owner: root
    group: root
    mode: '0444'
  register: newrelic_signing_key
- name: Jammy Repo
  include_tasks: jammy.yml
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_release'] == 'jammy'
- name: Noble Repo
  include_tasks: noble.yml
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_release'] == 'noble'
- name: Install newrelic-infra agent
  ansible.builtin.package:
    name: newrelic-infra
    state: present
  notify: Reload newrelic-infra service