---
- name: Initialize AIDE
  ansible.builtin.command:
    cmd: aide -c /etc/aide/aide.conf --init
    creates: /var/lib/aide/aide.db.new
  notify: Copy AIDE Database
- name: Copy AIDE Database
  ansible.builtin.copy:
    remote_src: true
    src: /var/lib/aide/aide.db.new
    dest: /var/lib/aide/aide.db
    owner: root
    group: root
    mode: '0400'
- name: Reload Chrony
  ansible.builtin.systemd:
    name: chrony
    masked: false
    state: restarted
    enabled: true
- name: Reload auditd
  ansible.builtin.systemd:
    name: auditd
    masked: false
    state: restarted
    enabled: true
