---
- name: Set Vars
  hosts: all
  tasks:
    - name: Set play var if not defined
      set_fact:
        play: "{{ play | default('plays/basic.yaml') }}"
- name: Basic
  hosts: all
  roles:
    - updated-system
    - schedule-reboot
    - role: auto-pull
      vars:
        auto_pull_play: "{{ play }}"
