---
- name: Set Vars
  hosts: all
  tasks:
    - name: Set play var if not defined
      set_fact:
        play: "{{ play | default('plays/edge.yaml') }}"
- name: Basic
  ansible.builtin.import_playbook: basic.yaml
- name: Edge
  hosts: all
  roles:
    - role: nodejs
      when: nodejs_enabled
    - role: java
      when: java_enabled
    - role: node-red
      when: node_red_enabled
    - role: cloudflared
      when: cloudflared_enabled
    - role: newrelic
      when: newrelic_enabled
    - role: falco
      when: falco_enabled
