---
- name: Basic
  ansible.builtin.import_playbook: basic.yaml
- name: Edge
  hosts: all
  roles:
    - role: coredns
      when: coredns_enabled
    - role: nodejs
      when: nodejs_enabled
    - role: java
      when: java_enabled
    - role: couchdb
      when: couchdb_enabled
    - role: node-red
      when: node_red_enabled
    - role: cloudflared
      when: cloudflared_enabled
    - role: newrelic
      when: newrelic_enabled
    - role: fluent-bit
      when: fluent_bit_enabled
    - role: falco
      when: falco_enabled
    - role: wazuh-indexer
      when: wazuh_indexer_enabled
    - role: ansible-wazuh-manager
      when: wazuh_manager_enabled
    - role: wazuh-dashboard
      when: wazuh_dashboard_enabled
    - role: ansible-wazuh-agent
      when: wazuh_agent_enabled
