---
- name: Set Vars
  hosts: all
  tasks:
    - name: Set play var if not defined
      set_fact:
        play: "{{ play | default('plays/harden.yaml') }}"
- name: Harden
  hosts: all
  roles:
    - hardened-system
    - role: auto-pull
      vars:
        auto_pull_cron_job_name: "ansible-pull-harden"
        auto_pull_play: "{{ play }}"
        auto_pull_cron_job_minute: "0"
        auto_pull_cron_job_hour: "0"
