---
- name: Set Vars
  hosts: all
  tasks:
    - name: Set play var if not defined
      set_fact:
        play: "{{ play | default('plays/java.yaml') }}"
- name: Basic
  ansible.builtin.import_playbook: basic.yaml
- name: Java
  hosts: all
  roles:
    - java
