---
  - name: Basic
    ansible.builtin.import_playbook: edge.yaml
# Certificates generation
  - hosts: all
    roles:
      - role: wazuh-indexer
        perform_installation: false
    become: false
    #become_user: root
    vars:
      indexer_node_master: true
      certs_gen_tool_version: "4.10"
      instances:
        node1:
          name: node-1       # Important: must be equal to indexer_node_name.
          ip: 127.0.0.1
          role: indexer
      macos_localhost: false
    tags:
      - generate-certs
# Single node
  - hosts: all
    become: true
    become_user: root
    roles:
      - role: wazuh-indexer
      - role: ansible-wazuh-manager
      - role: ansible-filebeat-oss
      - role: wazuh-dashboard
    vars:
      single_node: true
      minimum_master_nodes: 1
      indexer_node_master: true
      indexer_network_host: 127.0.0.1
      filebeat_node_name: node-1
      filebeat_output_indexer_hosts:
      - 127.0.0.1
      instances:
        node1:
          name: node-1       # Important: must be equal to indexer_node_name.
          ip: 127.0.0.1
          role: indexer
      ansible_shell_allow_world_readable_temp: true
