- name: Reload service
  ansible.builtin.systemd:
    daemon_reload: yes
    state: restarted
    name: uptime-kuma
    enabled: yes
    masked: no
    scope: system

- name: Install node modules
  become: true
  become_user: "uptime-kuma"
  ansible.builtin.command:
    cmd: npm ci --prefer-offline --no-audit --omit=dev
    chdir: /opt/{{ uptime_kuma_org }}/uptime-kuma

- name: Reload apparmor
  ansible.builtin.command:
    cmd: apparmor_parser -r -T -W /etc/apparmor.d/opt.{{ uptime_kuma_org }}.uptime-kuma.service
