---
- name: Ensure SSH is installed
  ansible.builtin.package:
    name: openssh-server
    state: present
- name: Start SSH
  ansible.builtin.systemd:
    name: ssh
    state: started
- name: Check if ufw is installed
  ansible.builtin.package:
    name: ufw
    state: present
- name: Allow SSH through firewall
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp
    direction: in
    src: "{{ item}}"
  with_items: "{{ debug_allowed_networks }}"
