---
- name: Start SSH
  ansible.builtin.systemd:
    name: ssh
    state: started
- name: Allow SSH through firewall
  community.general.ufw:
    rule: allow
    name: OpenSSH
    src: "{{ item}}"
  with_items: "{{ debug_allowed_networks }}"
