---
- name: Remove immutable attribute
  ansible.builtin.include_tasks: remove-immutable-to-files.yml

- name: Create uptime-kuma group
  ansible.builtin.group:
    name: uptime-kuma
    gid: "{{ uptime_kuma_gid }}"

- name: Create uptime-kuma user
  ansible.builtin.user:
    name: uptime-kuma
    uid: "{{ uptime_kuma_uid }}"
    group: uptime-kuma
    shell: /usr/sbin/nologin

- name: Create /opt/{{ uptime_kuma_org }} directory
  ansible.builtin.file:
    path: /opt/{{ uptime_kuma_org }}
    state: directory
    owner: "{{ uptime_kuma_uid }}"
    group: "{{ uptime_kuma_gid }}"
    mode: '0755'

- name: Create /opt/{{ uptime_kuma_org }}/uptime-kuma directory
  ansible.builtin.file:
    path: /opt/{{ uptime_kuma_org }}/uptime-kuma
    state: directory
    owner: "{{ uptime_kuma_uid }}"
    group: "{{ uptime_kuma_gid }}"
    mode: '0750'

- name: Fetch uptime-kuma
  become: true
  become_user: uptime-kuma
  ansible.builtin.git:
    repo: "{{ uptime_kuma_repo }}"
    dest: /opt/{{ uptime_kuma_org }}/uptime-kuma
    version: "{{ uptime_kuma_version }}"
  notify: Install node modules


- name: Copy apparmor profile to /etc/apparmor.d
  notify: Reload apparmor
  ansible.builtin.template:
    src: templates/uptime-kuma.apparmor.j2
    dest: /etc/apparmor.d/opt.{{ uptime_kuma_org }}.uptime-kuma.service
    mode: '0440'

- name: Copy uptime-kuma.service to /etc/systemd/system
  ansible.builtin.template:
    src: templates/uptime-kuma.service.j2
    dest: /etc/systemd/system/uptime-kuma.service
    mode: '0440'
  notify: Reload service

- name: Add immutable attribute
  ansible.builtin.include_tasks: add-immutable-to-files.yml