---
- name: Remove immutable attribute
  ansible.builtin.include_tasks: remove-immutable-to-files.yml
- name: Create node-red group
  ansible.builtin.group:
    name: node-red
    gid: "{{ node_red_gid }}"

- name: Create node-red user
  ansible.builtin.user:
    name: node-red
    uid: "{{ node_red_uid }}"
    group: node-red
    shell: /usr/sbin/nologin

- name: Create /opt/{{ node_red_org }} directory
  ansible.builtin.file:
    path: /opt/{{ node_red_org }}
    state: directory
    owner: "{{ node_red_uid }}"
    group: "{{ node_red_gid }}"
    mode: '0755'

- name: Create /opt/{{ node_red_org }}/node-red directory
  ansible.builtin.file:
    path: /opt/{{ node_red_org }}/node-red
    state: directory
    owner: "{{ node_red_uid }}"
    group: "{{ node_red_gid }}"
    mode: '0750'

- name: Copy package.json to /opt/{{ node_red_org }}/node-red
  ansible.builtin.copy:
    src: files/app/package.json
    dest: /opt/{{ node_red_org }}/node-red/package.json
    owner: "{{ node_red_uid }}"
    group: "{{ node_red_gid }}"
    mode: '0440'

- name: Copy package-lock.json to /opt/{{ node_red_org }}/node-red
  register: package_lock_json
  notify: Install node modules
  ansible.builtin.copy:
    src: files/app/package-lock.json
    dest: /opt/{{ node_red_org }}/node-red/package-lock.json
    owner: "{{ node_red_uid }}"
    group: "{{ node_red_gid }}"
    mode: '0440'
  

- name: Copy service.mjs to /opt/{{ node_red_org }}/node-red
  notify: Reload service
  ansible.builtin.copy:
    src: files/app/service.mjs
    dest: /opt/{{ node_red_org }}/node-red/service.mjs
    owner: "{{ node_red_uid }}"
    group: "{{ node_red_gid }}"
    mode: '0750'

- name: Copy apparmor profile to /etc/apparmor.d
  notify: Reload apparmor
  ansible.builtin.template:
    src: files/app/debian/node-red.apparmor.j2
    dest: /etc/apparmor.d/opt.{{ node_red_org }}.node-red.service
    mode: '0440'
- name: Copy node-red.service to /etc/systemd/system
  ansible.builtin.template:
    src: files/app/debian/node-red.service.j2
    dest: /etc/systemd/system/node-red.service
    mode: '0440'
  notify: Reload service
- name: Add immutable attribute
  ansible.builtin.include_tasks: add-immutable-to-files.yml