---
- name: Create cloudflared group
  ansible.builtin.group:
    name: cloudflared
    gid: "{{ cloudflared_gid }}"
- name: Create cloudflared user
  ansible.builtin.user:
    name: cloudflared
    uid: "{{ cloudflared_uid }}"
    group: cloudflared
    shell: /usr/sbin/nologin
- name: Create cloudflare log dir
  ansible.builtin.file:
    path: /var/log/cloudflared
    state: directory
    owner: cloudflared
    group: cloudflared
    mode: '0755'
- name: Create cloudflared config dir
  ansible.builtin.file:
    path: /etc/cloudflared
    state: directory
    owner: cloudflared
    group: cloudflared
    mode: '0700'
- name: Render cloudflared config
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/cloudflared/config.yaml
    owner: cloudflared
    group: cloudflared
    mode: '0600'
- name: Render cloudflared service
  notify: Reload cloudflared service
  ansible.builtin.template:
    src: cloudflared.service.j2
    dest: /etc/systemd/system/cloudflared.service
    owner: root
    group: root
    mode: '0600'
- name: Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu'
